task:
    name: building recovery
    timeout_in: 4h
    container:
      image: ubuntu:latest
      cpu: 16
      memory: 32G
      volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
    run_script: # To sync source
      - apt update && DEBIAN_FRONTEND="noninteractive" TZ="Asia/Jakarta" apt-get install -y tzdata curl git sudo
      - bash <(curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh)
      - git config --global user.name ""
      - git config --global user.email ""
      - mkdir linjetpbrp && cd linjetpbrp
      - /usr/local/bin/repo init -u https://github.com/PixelExperience/manifest -b twelve-plus -g default,-device,-mips,-darwin,-notdefault && repo sync --force-sync
      - git clone https://github.com/MikaelaNeia/android_device_xiaomi_agate -b twelve device/xiaomi/agate
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 50G
      - ccache -z
      - . build/envsetup.sh
      - lunch aosp_agate-userdebug
      - mka bacon
      - up=out/target/product/agate/PixelExperience*.zip
      - curl --upload-file $up https://transfer.sh/$($up); echo

