task:
    name: building rom
    timeout_in: 4h
    container:
      image: ubuntu:latest
      cpu: 8
      memory: 24G
      volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
    run_script: # To sync source
      - apt update && DEBIAN_FRONTEND="noninteractive" TZ="Asia/Jakarta" apt-get install -y tzdata curl git sudo
      - bash <(curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh)
      - git config --global user.name ""
      - git config --global user.email ""
      - mkdir rom && cd rom
      - /usr/local/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-19.1 -g default,-device,-mips,-darwin,-notdefault
      - repo sync --force-sync
      - git clone https://github.com/MikaelaNeia/android_device_xiaomi_agate -b lineage-19.1 device/xiaomi/agate
      - git clone https://github.com/MikaelaNeia/proprietary_vendor_xiaomi -b twelve
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 50G
      - ccache -z
      - . build/envsetup.sh
      - lunch lineage_agate-userdebug
      - brunch agate
      - curl -sL https://git.io/file-transfer | sh
      - ./transfer wet out/target/product/agate/lineage*.zip
