task:
    name: building recovery
    timeout_in: 4h
    container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
      volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
    run_script:
      - apt update && DEBIAN_FRONTEND="noninteractive" TZ="Asia/Jakarta" apt-get install -y tzdata curl git sudo
      - bash <(curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh)
    sync_script:
      - git config --global user.name ""
      - git config --global user.email ""
      - mkdir lineage && cd lineage
      - /usr/local/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-19.1 -g default,-device,-mips,-darwin,-notdefault && repo sync --force-sync
      - git clone https://github.com/MikaelaNeia/local_manifests -b lineage .repo/local_manifests
     build_script:
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 50G
      - ccache -z
      - source build/envsetup.sh
      - lunch lineage_agate-userdebug
      - brunch agate
      upload_script:
      - curl -sL https://git.io/file-transfer | sh
      - ./transfer wet out/target/product/agate/lineage-19.1*.zip

